services:

  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    container_name: server
    ports:
      - "9000:9000"
      - "5173:5173"
    depends_on:
      - db
    volumes:
      - ./server:/var/www/html
    environment:
      - DB_HOST=db
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
     - "8080:80"
    volumes:
      - ./docker/server/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./server:/var/www/html
    depends_on:
      - server

  db:
    image: mariadb:11.4
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

networks:
  app-network:
    driver: bridge